[package]
name = "inox2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22.0", features = ["serde"] }
image = "0.24.5"
indextree = { version = "4.5.0", features = ["deser"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_indextree = "0.2.0"
serde_json = "1.0.88"
thiserror = "1.0.37"
typetag = "0.2.3"

[dev-dependencies]
clap = "4.0.26"
miette = { version = "5.4.1", features = ["fancy"] }
