[package]
name = "inox2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22.0" }
glow = { version = "0.11.2", optional = true }
image = "0.24.5"
indextree = { version = "4.5.0" }
nom = "7.1.1"
owo-colors = { version = "3.5.0", optional = true }
thiserror = "1.0.37"

[dev-dependencies]
clap = { version = "4.0.26", features = ["derive"] }
glutin = "0.30.3"
glutin-winit = "0.2.1"
raw-window-handle = "0.5.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
winit = "0.27.5"

[features]
default = ["opengl"]
opengl = ["dep:glow"]
owo = ["dep:owo-colors"]

[[example]]
name = "render_inp"
required-features = ["opengl"]
