[package]
name = "inox2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
thiserror = "1.0.37"

[dev-dependencies]
glutin = "0.30.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
winit = "0.27.5"
