on: [push, pull_request]

name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: "aarch64-unknown-linux-gnu" }
          - { os: ubuntu-latest, target: "x86_64-unknown-linux-gnu" }
          - { os: ubuntu-latest, target: "x86_64-pc-windows-gnu" }
          - { os: ubuntu-latest, target: "wasm32-unknown-unknown" }
          - { os: macos-latest, target: "x86_64-apple-darwin" }
          - { os: macos-latest, target: "aarch64-apple-ios" }
          - { os: macos-latest, target: "x86_64-apple-ios" }
          - { os: windows-latest, target: "x86_64-pc-windows-msvc" }
        renderer:
          - opengl
          - wgpu

    steps:

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          override: true

      - name: Setup aarch64
        if: matrix.config.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt install gcc-aarch64-linux-gnu
          echo "[target.aarch64-unknown-linux-gnu]" >> ~/.cargo/config
          echo "linker = \"aarch64-linux-gnu-gcc\"" >> ~/.cargo/config

      - name: Build (OpenGL)
        if: matrix.renderer == 'opengl'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features opengl,owo --all-targets --target=${{ matrix.config.target }}

      - name: Build Example (OpenGL)
        if: matrix.renderer == 'opengl'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example render_opengl --no-default-features --features opengl,owo --all-targets --target=${{ matrix.config.target }}

      - name: Build (WGPU)
        if: matrix.renderer == 'wgpu'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features wgpu,owo --all-targets --target=${{ matrix.config.target }}

      - name: Build Example (WGPU)
        if: matrix.renderer == 'wgpu'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example render_wgpu --no-default-features --features wgpu,owo --all-targets --target=${{ matrix.config.target }}
